### ISSUE TITLE
Add ACM Board coverage to the template

### ISSUE THREAD

**Issue by ArshMalik02** [uclaacm/committee-website-template-cms#35]
## Overview

The template currently works only for the ACM committees. We want to expand its use to set up a website for the ACM Board as well.

## Tasks

- [x] Update the source code to have the Board listed as one of the committees.

- [x] The team page should list all internal and external board officers.
- [x] The events page should list all events tagged as "General" in the events spreadsheet.
- [x] The landing page should correctly read data for the Board from the committee info spreadsheet.
- [x] Create two design assets for Board: acm.board logo and acm board background for the landing page.

## Deadline

We need to have the board website up and running before Week 0 of Fall 2023.

**Comment by ArshMalik02** [comment]
All tasks completed 🎉 closing this issue!
